apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquila
spec:
  selector:
    matchLabels:
      app: aquila
  replicas: 1 
  template: 
    metadata:
      labels:
        app: aquila
    spec:
      containers:
      - name: aquila
        image: riyazshaik123/aquila2:latest1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aquila
spec:
  type: LoadBalancer
  selector:
    app: aquila
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
